name: Java CI - Run Unit Tests

run-name: Unit tests on push to main branch

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-java:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Verify and test with Maven
        run: mvn clean test